-- ============================================================
--  うさぎ鉄道 電力・車両保守システム (URMS) スキーマ定義 (Oracle 11g 向け)
--  作成: 2009/04  うさぎ電機システムズ 交通システム部
--  変更: 2013/10  車両保守 (検修) サブシステム追加
--        2016/06  メーカー修理依頼 (REPAIR_ORDER) 追加
-- ============================================================

CREATE SEQUENCE SEQ_MEASUREMENT START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ALARM       START WITH 101  INCREMENT BY 1;
CREATE SEQUENCE SEQ_OUTAGE      START WITH 42   INCREMENT BY 1;
CREATE SEQUENCE SEQ_FAILURE     START WITH 5    INCREMENT BY 1;
CREATE SEQUENCE SEQ_REPAIR      START WITH 3    INCREMENT BY 1;
-- 帳票番号 (P-YY-NNNN / F-YY-NNNN / R-YY-NNNN) 採番用
CREATE SEQUENCE SEQ_OUTAGE_NO   START WITH 42   INCREMENT BY 1;
CREATE SEQUENCE SEQ_FAILURE_NO  START WITH 5    INCREMENT BY 1;
CREATE SEQUENCE SEQ_REPAIR_NO   START WITH 3    INCREMENT BY 1;

-- ------------------------------------------------------------
--  電力管理
-- ------------------------------------------------------------

-- 変電所・き電区分所マスタ
CREATE TABLE SUBSTATION (
    SUBSTATION_CODE    VARCHAR2(4)    NOT NULL,
    SUBSTATION_NAME    VARCHAR2(40)   NOT NULL,
    KIND               VARCHAR2(4)    NOT NULL,
    LINE_NAME          VARCHAR2(20)   NOT NULL,
    KM_POST            NUMBER(7,3)    NOT NULL,
    FEED_VOLTAGE_V     NUMBER(5)      NOT NULL,
    TELEMETRY_FLG      CHAR(1)        DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_SUBSTATION PRIMARY KEY (SUBSTATION_CODE),
    CONSTRAINT CK_SUBSTATION_KIND CHECK (KIND IN ('SS', 'SP', 'SSP'))
);

-- 遮断器
CREATE TABLE BREAKER (
    BREAKER_ID         NUMBER(10)     NOT NULL,
    SUBSTATION_CODE    VARCHAR2(4)    NOT NULL,
    BREAKER_CODE       VARCHAR2(8)    NOT NULL,
    BREAKER_NAME       VARCHAR2(40)   NOT NULL,
    STATE              VARCHAR2(8)    DEFAULT 'CLOSED' NOT NULL,
    RATED_CURRENT_A    NUMBER(5)      NOT NULL,
    VERSION            NUMBER(10)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_BREAKER PRIMARY KEY (BREAKER_ID),
    CONSTRAINT UK_BREAKER UNIQUE (SUBSTATION_CODE, BREAKER_CODE),
    CONSTRAINT FK_BREAKER_SS FOREIGN KEY (SUBSTATION_CODE) REFERENCES SUBSTATION (SUBSTATION_CODE),
    CONSTRAINT CK_BREAKER_STATE CHECK (STATE IN ('CLOSED', 'OPEN', 'TRIPPED'))
);

-- 計測値 (RTU からの 1 時間ごとの伝文)
CREATE TABLE MEASUREMENT (
    MEASUREMENT_ID     NUMBER(19)     NOT NULL,
    SUBSTATION_CODE    VARCHAR2(4)    NOT NULL,
    MEASURED_AT        TIMESTAMP      NOT NULL,
    VOLTAGE_V          NUMBER(5)      NOT NULL,
    CURRENT_A          NUMBER(5)      NOT NULL,
    ENERGY_KWH         NUMBER(7)      NOT NULL,
    QUALITY            CHAR(1)        DEFAULT '0' NOT NULL,
    CONSTRAINT PK_MEASUREMENT PRIMARY KEY (MEASUREMENT_ID),
    CONSTRAINT UK_MEASUREMENT UNIQUE (SUBSTATION_CODE, MEASURED_AT),
    CONSTRAINT FK_MEASUREMENT_SS FOREIGN KEY (SUBSTATION_CODE) REFERENCES SUBSTATION (SUBSTATION_CODE)
);

-- 警報
CREATE TABLE ALARM (
    ALARM_ID           NUMBER(19)     NOT NULL,
    SUBSTATION_CODE    VARCHAR2(4)    NOT NULL,
    BREAKER_CODE       VARCHAR2(8),
    OCCURRED_AT        TIMESTAMP      NOT NULL,
    ALARM_LEVEL        VARCHAR2(6)    NOT NULL,
    ALARM_CODE         VARCHAR2(6)    NOT NULL,
    MESSAGE            VARCHAR2(200)  NOT NULL,
    ACK_FLG            CHAR(1)        DEFAULT 'N' NOT NULL,
    ACK_BY             VARCHAR2(20),
    ACK_AT             TIMESTAMP,
    CONSTRAINT PK_ALARM PRIMARY KEY (ALARM_ID),
    CONSTRAINT FK_ALARM_SS FOREIGN KEY (SUBSTATION_CODE) REFERENCES SUBSTATION (SUBSTATION_CODE),
    CONSTRAINT CK_ALARM_LEVEL CHECK (ALARM_LEVEL IN ('MAJOR', 'MINOR', 'NOTICE'))
);
CREATE INDEX IX_ALARM_OCCURRED ON ALARM (OCCURRED_AT);

-- 停電作業申請 (き電停止申請)
CREATE TABLE OUTAGE_REQUEST (
    OUTAGE_ID          NUMBER(19)     NOT NULL,
    REQUEST_NO         VARCHAR2(10)   NOT NULL,
    BREAKER_ID         NUMBER(10)     NOT NULL,
    WORK_DATE          DATE           NOT NULL,
    START_TIME         VARCHAR2(5)    NOT NULL,
    END_TIME           VARCHAR2(5)    NOT NULL,
    DESCRIPTION        VARCHAR2(200)  NOT NULL,
    STATUS             VARCHAR2(12)   DEFAULT 'REQUESTED' NOT NULL,
    REQUESTED_BY       VARCHAR2(20)   NOT NULL,
    REQUESTED_AT       TIMESTAMP      DEFAULT SYSDATE NOT NULL,
    APPROVED_BY        VARCHAR2(20),
    APPROVED_AT        TIMESTAMP,
    REMARKS            VARCHAR2(200),
    VERSION            NUMBER(10)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_OUTAGE_REQUEST PRIMARY KEY (OUTAGE_ID),
    CONSTRAINT UK_OUTAGE_REQUEST_NO UNIQUE (REQUEST_NO),
    CONSTRAINT FK_OUTAGE_BREAKER FOREIGN KEY (BREAKER_ID) REFERENCES BREAKER (BREAKER_ID),
    CONSTRAINT CK_OUTAGE_STATUS CHECK (STATUS IN ('REQUESTED', 'APPROVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED'))
);

-- ------------------------------------------------------------
--  車両保守 (検修)
-- ------------------------------------------------------------

-- 編成
CREATE TABLE FORMATION (
    FORMATION_NO       VARCHAR2(6)    NOT NULL,
    SERIES             VARCHAR2(10)   NOT NULL,
    CAR_COUNT          NUMBER(2)      NOT NULL,
    DEPOT              VARCHAR2(20)   NOT NULL,
    IN_SERVICE_ON      DATE           NOT NULL,
    TOTAL_KM           NUMBER(9)      NOT NULL,
    LAST_KOBAN_ON      DATE           NOT NULL,
    LAST_JUYOBU_ON     DATE           NOT NULL,
    LAST_ZENPAN_ON     DATE           NOT NULL,
    KM_SINCE_JUYOBU    NUMBER(7)      NOT NULL,
    STATUS             VARCHAR2(16)   DEFAULT 'IN_SERVICE' NOT NULL,
    CONSTRAINT PK_FORMATION PRIMARY KEY (FORMATION_NO),
    CONSTRAINT CK_FORMATION_STATUS CHECK (STATUS IN ('IN_SERVICE', 'IN_DEPOT', 'OUT_OF_SERVICE'))
);

-- 車両
CREATE TABLE CAR (
    CAR_NO             VARCHAR2(6)    NOT NULL,
    FORMATION_NO       VARCHAR2(6)    NOT NULL,
    POSITION           NUMBER(2)      NOT NULL,
    CAR_TYPE           VARCHAR2(4)    NOT NULL,
    CONSTRAINT PK_CAR PRIMARY KEY (CAR_NO),
    CONSTRAINT FK_CAR_FORMATION FOREIGN KEY (FORMATION_NO) REFERENCES FORMATION (FORMATION_NO)
);

-- 搭載機器 (製造番号をキーとしてライフサイクル管理)
CREATE TABLE EQUIPMENT (
    SERIAL_NO          VARCHAR2(12)   NOT NULL,
    EQUIPMENT_TYPE     VARCHAR2(8)    NOT NULL,
    MODEL              VARCHAR2(20)   NOT NULL,
    MAKER              VARCHAR2(40)   NOT NULL,
    MANUFACTURED_ON    DATE           NOT NULL,
    CAR_NO             VARCHAR2(6),
    INSTALLED_ON       DATE,
    CONSTRAINT PK_EQUIPMENT PRIMARY KEY (SERIAL_NO),
    CONSTRAINT FK_EQUIPMENT_CAR FOREIGN KEY (CAR_NO) REFERENCES CAR (CAR_NO),
    CONSTRAINT CK_EQUIPMENT_TYPE CHECK (EQUIPMENT_TYPE IN ('VVVF', 'SIV', 'BCU'))
);

-- 故障記録
CREATE TABLE FAILURE_RECORD (
    FAILURE_ID         NUMBER(19)     NOT NULL,
    FAILURE_NO         VARCHAR2(10)   NOT NULL,
    SERIAL_NO          VARCHAR2(12)   NOT NULL,
    FORMATION_NO       VARCHAR2(6)    NOT NULL,
    OCCURRED_AT        TIMESTAMP      NOT NULL,
    SYMPTOM            VARCHAR2(200)  NOT NULL,
    FAILURE_CODE       VARCHAR2(8),
    SEVERITY           CHAR(1)        NOT NULL,
    STATUS             VARCHAR2(16)   DEFAULT 'OPEN' NOT NULL,
    REPORTED_BY        VARCHAR2(20)   NOT NULL,
    VERSION            NUMBER(10)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_FAILURE_RECORD PRIMARY KEY (FAILURE_ID),
    CONSTRAINT UK_FAILURE_NO UNIQUE (FAILURE_NO),
    CONSTRAINT FK_FAILURE_EQUIPMENT FOREIGN KEY (SERIAL_NO) REFERENCES EQUIPMENT (SERIAL_NO),
    CONSTRAINT CK_FAILURE_SEVERITY CHECK (SEVERITY IN ('A', 'B', 'C')),
    CONSTRAINT CK_FAILURE_STATUS CHECK (STATUS IN ('OPEN', 'INVESTIGATING', 'REPAIR_REQUESTED', 'REPAIRED', 'CLOSED'))
);

-- メーカー修理依頼
CREATE TABLE REPAIR_ORDER (
    REPAIR_ID          NUMBER(19)     NOT NULL,
    ORDER_NO           VARCHAR2(10)   NOT NULL,
    FAILURE_ID         NUMBER(19)     NOT NULL,
    MAKER              VARCHAR2(40)   NOT NULL,
    REQUESTED_AT       TIMESTAMP      NOT NULL,
    REQUESTED_BY       VARCHAR2(20)   NOT NULL,
    STATUS             VARCHAR2(12)   DEFAULT 'REQUESTED' NOT NULL,
    PROGRESS_NOTE      VARCHAR2(400),
    UPDATED_BY         VARCHAR2(20),
    UPDATED_AT         TIMESTAMP,
    VERSION            NUMBER(10)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_REPAIR_ORDER PRIMARY KEY (REPAIR_ID),
    CONSTRAINT UK_REPAIR_ORDER_NO UNIQUE (ORDER_NO),
    CONSTRAINT FK_REPAIR_FAILURE FOREIGN KEY (FAILURE_ID) REFERENCES FAILURE_RECORD (FAILURE_ID),
    CONSTRAINT CK_REPAIR_STATUS CHECK (STATUS IN ('REQUESTED', 'RECEIVED', 'REPAIRING', 'RETURNED'))
);
